env:
  global:
  - GIT_NAME: "'Markdown autodeploy'"
  - GIT_EMAIL: blin@cs.wisc.edu
  - GH_REF: git@github.com:opensciencegrid/technology.git
language: python
before_script:
- pip install mkdocs
- pip install MarkdownHighlight
- pip install pygments
script:
- if [ "${TRAVIS_PULL_REQUEST}" == "false" ] && [ "${TRAVIS_BRANCH}" == "master" ]; then ./travis/run_on_non_pull_requests.sh; else ./travis/run_on_pull_requests.sh; fi
