site_name: OSG Technology Area
site_url: https://opensciencegrid.github.io/technology
repo_url: https://github.com/opensciencegrid/technology
theme: readthedocs
theme_dir: osgthedocs

extra_css:
  - css/extra.css

pages:
  - Home: 'index.md'
  - Contact Us: 'contact.md'
  - Meeting Notes: 'meetings.md'
  - Software:
    - Migrating Documents to Markdown: 'software/markdown-migration.md'
    - New Team Member: 'software/new-team-member.md'
  - Release:
    - How to Cut a Release: 'release/cut-sw-release.md'
    - How to Cut a Data Release: 'release/cut-data-release.md'
  - Policy:
    - 'GUMS Retirement': 'policy/gums-retire.md'
    - 'BeStMan2 Retirement': 'policy/bestman2-retire.md'
    - 'VOMS Admin Retirement': 'policy/voms-admin-retire.md'
    - 'Release Series Support': 'policy/release-series.md'
    - 'Globus Toolkit Support': 'policy/globus-toolkit.md'
  - Historical Transitions:
    - 'SHA-2 Support': 'projects/sha2-support.md'
  - February 27, 2017: 'meetings/2017/TechArea20170227.md'
  - April 17, 2017: 'meetings/2017/TechArea20170417.md'
  - April 24, 2017: 'meetings/2017/TechArea20170424.md'
  - May 1, 2017: 'meetings/2017/TechArea20170501.md'
  - May 8, 2017: 'meetings/2017/TechArea20170508.md'
  - May 15, 2017: 'meetings/2017/TechArea20170515.md'
  - May 22, 2017: 'meetings/2017/TechArea20170522.md'
  - May 30, 2017: 'meetings/2017/TechArea20170530.md'
  - June 6, 2017: 'meetings/2017/TechArea20170605.md'
  - June 12, 2017: 'meetings/2017/TechArea20170612.md'
  - June 19, 2017: 'meetings/2017/TechArea20170619.md'
  - June 26, 2017: 'meetings/2017/TechArea20170626.md'
  - July 3, 2017: 'meetings/2017/TechArea20170703.md'
  - July 10, 2017: 'meetings/2017/TechArea20170710.md'
  - July 17, 2017: 'meetings/2017/TechArea20170717.md'
  - July 24, 2017: 'meetings/2017/TechArea20170724.md'
  - July 31, 2017: 'meetings/2017/TechArea20170731.md'
  - August 7, 2017: 'meetings/2017/TechArea20170807.md'

markdown_extensions:
  - admonition
  - codehilite

